[package]
name = "aleph_ollama"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "aleph_ollama"
path = "src/lib.rs"
